//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVotaciones.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Voto
    {
        public int Id { get; set; }
        public int VotanteId { get; set; }
        public int CandidatoId { get; set; }
        [JsonIgnore]
        public virtual Candidato Candidato { get; set; }
        [JsonIgnore]
        public virtual Votante Votante { get; set; }
    }
}
